const KEY="lotus365_html_v1";
const seed={customers:[{id:"C001",name:"Shree Enterprise",phone:"9876543210",city:"Rajkot",balance:42000},{id:"C002",name:"Kisan Traders",phone:"9825012345",city:"Morbi",balance:18500}],products:[{id:"P001",name:"Groundnut Oil 1L",code:"GO-1L",category:"Edible Oil",stock:125,price:165},{id:"P002",name:"Groundnut Oil 5L",code:"GO-5L",category:"Edible Oil",stock:64,price:780},{id:"P003",name:"Refined Oil 1L",code:"RO-1L",category:"Edible Oil",stock:38,price:145}],sales:[{id:"S001",customer:"Shree Enterprise",amount:24750,status:"Paid",date:"2026-10-05"},{id:"S002",customer:"Kisan Traders",amount:12800,status:"Pending",date:"2026-10-04"}],purchase:[{id:"PCH001",supplier:"Apex Distributors",amount:35000,status:"Received",date:"2026-10-03"}],expenses:[{id:"E001",title:"Office Expense",amount:4500,date:"2026-10-02"}]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||seed; let page="dashboard";
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)); save();
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const sum=(arr,key)=>arr.reduce((a,x)=>a+Number(x[key]||0),0);
function nav(){document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.getElementById("quickAdd").onclick=()=>openForm(page==="customers"?"customers":page==="products"?"products":"sales")}

function render(){document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const names={dashboard:"Dashboard",customers:"Customers",products:"Products",inventory:"Inventory",sales:"Sales",purchase:"Purchase",accounting:"Accounting",reports:"Reports",settings:"Settings"};document.getElementById("pageName").textContent=names[page];document.getElementById("title").textContent=page==="dashboard"?"Executive Dashboard":names[page];document.getElementById("content").innerHTML=pages[page]();bind()}
function dashboard(){const sales=sum(db.sales,"amount"),purchase=sum(db.purchase,"amount"),out=sum(db.customers,"balance"),stock=db.products.reduce((a,x)=>a+x.stock,0);return `
<div class="grid"><div class="card kpi"><div class="label">Total Sales</div><div class="value">${money(sales)}</div><div class="up">↑ Live local data</div></div><div class="card kpi"><div class="label">Purchases</div><div class="value">${money(purchase)}</div><div class="up">↑ Current period</div></div><div class="card kpi"><div class="label">Receivables</div><div class="value">${money(out)}</div><div class="up">Customer outstanding</div></div><div class="card kpi"><div class="label">Stock Units</div><div class="value">${stock}</div><div class="up">${db.products.filter(x=>x.stock<40).length} low-stock items</div></div></div>
<div class="two"><div class="card section"><div class="section-head"><h3>Sales Overview</h3><span class="link">This period</span></div><div class="chart">${[45,65,52,78,62,88,70].map((h,i)=>`<div class="bar" style="height:${h}%"><i>${["M","T","W","T","F","S","S"][i]}</i></div>`).join("")}</div></div>
<div class="card section"><div class="section-head"><h3>Inventory Alerts</h3><span class="link" onclick="page='inventory';render()">View all</span></div>${db.products.filter(x=>x.stock<40).map(x=>`<div class="stat-row"><span>${x.name}</span><b class="danger">${x.stock} left</b></div>`).join("")||'<div class="empty">No low-stock items</div>'}</div></div>
<div class="card section"><div class="section-head"><h3>Recent Sales</h3><span class="link" onclick="page='sales';render()">View all</span></div>${table(["Invoice","Customer","Amount","Status","Date"],db.sales.slice(-5).reverse().map(x=>[x.id,x.customer,money(x.amount),`<span class="badge">${x.status}</span>`,x.date]))}</div>`}

const table=(heads,rows)=>`<div class="table-wrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
function listPage(type,title,heads,rows,button){return `<div class="card section"><div class="toolbar"><input id="search" class="search" placeholder="Search ${title.toLowerCase()}..."><button class="primary" onclick="openForm('${type}')">＋ Add ${button||title.slice(0,-1)}</button></div><div id="list">${table(heads,rows)}</div></div>`}
const pages={
dashboard:dashboard,
customers:()=>listPage("customers","Customers",["ID","Name","Phone","City","Outstanding"],db.customers.map(x=>[x.id,x.name,x.phone,x.city,money(x.balance)]),"Customer"),
products:()=>listPage("products","Products",["Code","Product","Category","Stock","Price"],db.products.map(x=>[x.code,x.name,x.category,`<span class="badge">${x.stock}</span>`,money(x.price)]),"Product"),
inventory:()=>`<div class="grid"><div class="card kpi"><div class="label">Total Items</div><div class="value">${db.products.length}</div></div><div class="card kpi"><div class="label">Total Units</div><div class="value">${db.products.reduce((a,x)=>a+x.stock,0)}</div></div><div class="card kpi"><div class="label">Low Stock</div><div class="value danger">${db.products.filter(x=>x.stock<40).length}</div></div><div class="card kpi"><div class="label">Inventory Value</div><div class="value">${money(db.products.reduce((a,x)=>a+x.stock*x.price,0))}</div></div></div><div class="card section"><div class="section-head"><h3>Stock Ledger</h3><button class="primary" onclick="openForm('stock')">＋ Stock Adjustment</button></div>${table(["Code","Product","Current Stock","Unit Price","Value","Status"],db.products.map(x=>[x.code,x.name,x.stock,money(x.price),money(x.stock*x.price),x.stock<40?'<span class="badge">Low Stock</span>':'<span class="badge">Healthy</span>']))}</div>`,
sales:()=>listPage("sales","Sales",["Invoice","Customer","Amount","Status","Date"],db.sales.map(x=>[x.id,x.customer,money(x.amount),`<span class="badge">${x.status}</span>`,x.date]),"Sales Invoice"),
purchase:()=>listPage("purchase","Purchase",["Bill","Supplier","Amount","Status","Date"],db.purchase.map(x=>[x.id,x.supplier,money(x.amount),`<span class="badge">${x.status}</span>`,x.date]),"Purchase"),
accounting:()=>`<div class="grid"><div class="card kpi"><div class="label">Sales</div><div class="value">${money(sum(db.sales,"amount"))}</div></div><div class="card kpi"><div class="label">Purchase</div><div class="value">${money(sum(db.purchase,"amount"))}</div></div><div class="card kpi"><div class="label">Expenses</div><div class="value">${money(sum(db.expenses,"amount"))}</div></div><div class="card kpi"><div class="label">Gross Movement</div><div class="value">${money(sum(db.sales,"amount")-sum(db.purchase,"amount")-sum(db.expenses,"amount"))}</div></div></div><div class="card section"><div class="section-head"><h3>Expense Ledger</h3><button class="primary" onclick="openForm('expense')">＋ Add Expense</button></div>${table(["ID","Description","Amount","Date"],db.expenses.map(x=>[x.id,x.title,money(x.amount),x.date]))}</div>`,
reports:()=>`<div class="grid"><div class="card section"><h3>Sales Report</h3><div class="value" style="font-size:25px;margin-top:12px">${money(sum(db.sales,"amount"))}</div></div><div class="card section"><h3>Purchase Report</h3><div class="value" style="font-size:25px;margin-top:12px">${money(sum(db.purchase,"amount"))}</div></div><div class="card section"><h3>Receivable Report</h3><div class="value" style="font-size:25px;margin-top:12px">${money(sum(db.customers,"balance"))}</div></div><div class="card section"><h3>Inventory Report</h3><div class="value" style="font-size:25px;margin-top:12px">${money(db.products.reduce((a,x)=>a+x.stock*x.price,0))}</div></div></div>`,
settings:()=>`<div class="card section settings"><h3>Company & System Settings</h3><div class="notice">This HTML/CSS/JavaScript edition is fully browser-based for the current build stage. Records are stored locally in this browser so data survives refreshes. No demo button is pretending to save to a server.</div><div class="stat-row"><span>Company</span><b>Default Company</b></div><div class="stat-row"><span>Application</span><b>LOTUS 365 ERP</b></div><div class="stat-row"><span>Build</span><b>HTML + CSS + JavaScript</b></div><button class="btn danger" onclick="if(confirm('Clear all local ERP data and restore starter records?')){localStorage.removeItem(KEY);location.reload()}">Reset local data</button></div>`
};
function openForm(type){const forms={
customers:["New Customer",[["name","Customer Name","text"],["phone","Phone","text"],["city","City","text"],["balance","Opening Outstanding","number"]]],
products:["New Product",[["name","Product Name","text"],["code","Product Code","text"],["category","Category","text"],["stock","Opening Stock","number"],["price","Selling Price","number"]]],
sales:["New Sales Invoice",[["customer","Customer","text"],["amount","Amount","number"],["status","Status","select:Pending,Paid,Partial"]]],
purchase:["New Purchase Bill",[["supplier","Supplier","text"],["amount","Amount","number"],["status","Status","select:Draft,Received,Pending"]]],
expense:["New Expense",[["title","Description","text"],["amount","Amount","number"]]],
stock:["Stock Adjustment",[["code","Product Code","text"],["qty","Quantity (+/-)","number"]]]
};const f=forms[type]||forms.sales;document.getElementById("modalTitle").textContent=f[0];document.getElementById("recordForm").innerHTML='<div class="form">'+f[1].map(([n,l,t])=>t.startsWith("select:")?`<div class="field"><label>${l}</label><select name="${n}">${t.split(":")[1].split(",").map(o=>`<option>${o}</option>`).join("")}</select></div>`:`<div class="field"><label>${l}</label><input name="${n}" type="${t}" required></div>`).join("")+'<div class="form-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="primary">Save Record</button></div>';document.getElementById("modal").classList.remove("hidden");document.getElementById("recordForm").onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const id=type==="customers"?"C"+String(db.customers.length+1).padStart(3,"0"):type==="products"?"P"+String(db.products.length+1).padStart(3,"0"):type==="sales"?"S"+String(db.sales.length+1).padStart(3,"0"):type==="purchase"?"PCH"+String(db.purchase.length+1).padStart(3,"0"):type==="expense"?"E"+String(db.expenses.length+1).padStart(3,"0"):null;if(type==="stock"){const p=db.products.find(x=>x.code===o.code);if(p)p.stock+=Number(o.qty);else alert("Product code not found.");}else{if(type==="customers"){o.id=id;o.balance=Number(o.balance||0);db.customers.push(o)}if(type==="products"){o.id=id;o.stock=Number(o.stock||0);o.price=Number(o.price||0);db.products.push(o)}if(type==="sales"){o.id=id;o.amount=Number(o.amount);o.date=new Date().toISOString().slice(0,10);db.sales.push(o)}if(type==="purchase"){o.id=id;o.amount=Number(o.amount);o.date=new Date().toISOString().slice(0,10);db.purchase.push(o)}if(type==="expense"){o.id=id;o.amount=Number(o.amount);o.date=new Date().toISOString().slice(0,10);db.expenses.push(o)}}save();closeModal();render()}}
function closeModal(){document.getElementById("modal").classList.add("hidden")}document.getElementById("closeModal").onclick=closeModal;document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
function bind(){const s=document.getElementById("search");if(s)s.oninput=()=>{const q=s.value.toLowerCase();document.querySelectorAll("#list tbody tr").forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?"":"none")}}
nav();render();